{% set name = "clisops" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e118045f88114699763f54da33665e55e8164067ce8cc05d355ecb6908a8980d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - flit_core >=3.9,<4.0
    - pip
  run:
    - python >=3.9
    - bottleneck >=1.3.1
    - cartopy >=0.23
    - cf_xarray >=0.8.6
    - cftime >=1.4.1
    - dask >=2023.6.0
    - filelock >=3.15.4"
    - geopandas >=0.11.0
    - loguru >=0.5.3
    - numpy >=1.23.0,<2.1
    - packaging >=23.2.0
    - pandas >=1.5.0
    - platformdirs >=4.0
    - pooch >=1.8.0
    - pyproj >=3.3.0
    - roocs-grids >=0.1.2
    - roocs-utils >=0.6.7,<0.7
    - scipy >=1.9.0
    - shapely >=1.9
    - xarray >=2022.6.0
  run_constrained:
    - xesmf >=0.8.2

test:
  imports:
    - clisops
  requires:
    - git  # Required by GitPython
    - gitpython
    - netCDF4 >=1.4
    - pip
    - pytest >=8.0.0
    - pytest-loguru >=0.3.0
    - pytest-xdist >=3.2
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://pypi.org/project/clisops/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CLISOPS - Climate simulation operations.
  description: |
    The clisops package (pronounced "clie-sops") provides a python library for running
    data-reduction operations on xarray data sets or files that can be interpreted by xarray.
    These basic operations (subsetting, averaging and regridding) are likely to work
    where data structures are NetCDF-centric, such as those found in ESGF data sets.
  doc_url: https://clisops.readthedocs.io/en/latest/
  dev_url: https://github.com/roocs/clisops

extra:
  recipe-maintainers:
    - ellesmith88
    - Zeitsperre
    - agstephens
    - cehbrecht
