{% set name = "clisops" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c9a50e87ee8e4bf03af82bf0bacc74f591837841d760c09241cf2f5008627f9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python >=3.8
    - bottleneck >=1.3.1
    - cf_xarray >=0.7.0
    - cftime >=1.4.1
    - dask >=2.6.0
    - geopandas >=0.11.0
    - loguru >=0.5.3
    - netCDF4 >=1.4
    - numpy >=1.16
    - packaging
    - pandas >=1.0.3
    - poppler >=0.67
    - pooch
    - pyproj >=2.5
    - requests >=2.0
    - roocs-utils >=0.6.4,<0.7
    - shapely >=1.9
    - xarray >=0.21
    - xesmf >=0.6.3

test:
  imports:
    - clisops

about:
  home: https://pypi.org/project/clisops/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: clisops - climate simulation operations
  description: |
    The clisops package (pronounced "clie-sops") provides a python library for running
    data-reduction operations on xarray data sets or files
    that can be interpreted by xarray. These basic operations (subsetting, averaging and
    regridding) are likely to work where data structures are NetCDF-centric, such as those
    found in ESGF data sets.
  doc_url: https://clisops.readthedocs.io/en/latest/
  dev_url: https://github.com/roocs/clisops

extra:
  recipe-maintainers:
    - ellesmith88
    - Zeitsperre
    - agstephens
    - cehbrecht
