{% set name = "clisops" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0fd34ee51ce181fed9b2130b33e10e477a52b9db715143f12b2696d1b76c131

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - flit
    - pip
  run:
    - python >=3.9
    - bottleneck >=1.3.1
    - cf_xarray >=0.8.6
    - cftime >=1.4.1
    - dask >=2.6.0
    - geopandas >=0.11.0
    - loguru >=0.5.3
    - netCDF4 >=1.4
    - numba  # Must be specified for xemsf (fixed with v0.7.0)
    - numpy >=1.16
    - packaging
    - pandas >=1.0.3
    - pooch
    - pyproj >=3.3.0
    - requests >=2.0
    - roocs-utils >=0.6.4,<0.7
    - roocs-grids >=0.1.2
    - shapely >=1.9
    - sparse >=0.8.0  # Must be specified for xemsf (fixed with v0.7.0)
    - xarray >=0.21,<2023.3.0 # Remove pin when xarray is fixed (see: https://github.com/pydata/xarray/issues/7794)
    - xesmf >=0.8.2

test:
  imports:
    - clisops
  requires:
    - git  # Required by GitPython
    - gitpython
    - pip
    - pytest
    - pytest-loguru
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://pypi.org/project/clisops/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CLISOPS - Climate simulation operations.
  description: |
    The clisops package (pronounced "clie-sops") provides a python library for running
    data-reduction operations on xarray data sets or files that can be interpreted by xarray.
    These basic operations (subsetting, averaging and regridding) are likely to work
    where data structures are NetCDF-centric, such as those found in ESGF data sets.
  doc_url: https://clisops.readthedocs.io/en/latest/
  dev_url: https://github.com/roocs/clisops

extra:
  recipe-maintainers:
    - ellesmith88
    - Zeitsperre
    - agstephens
    - cehbrecht
